## import

importの使い方

In [6]:
import numpy as np
#asは別名でのインポート

npモジュールのrandom.randnアトリビュートを利用したい場合はnp.の後に続ける

In [20]:
np.random.randn(6,4)
#6行４列のランダムな数値を作成

array([[ 0.04822789, -0.93602346, -0.34281877, -1.24435829],
       [ 0.66982774, -0.11823476, -0.60714002, -0.43373179],
       [-0.32251316, -0.90327934,  1.32866824,  0.02128651],
       [ 1.9904953 ,  0.44685733,  1.03125264, -1.74046935],
       [-0.03472776, -0.47581373, -0.34603549, -0.70830199],
       [-0.24497281, -0.58713459,  0.69614693, -0.16723186]])

In [13]:
import pandas as pd

In [19]:
pd.DataFrame(np.random.randn(6,4))

0         1         2         3
0 -0.718674 -1.452721  1.369014  0.653765
1  0.520317 -1.256160  0.647050  0.830919
2 -0.376819  0.719480  0.743324  1.770880
3  1.489213  0.576553 -0.144334  0.930230
4  0.424244  0.004029  0.077968  0.068197
5  0.578882 -1.597735  0.314197 -0.150012

では、どのくらいの関数(method,attribute)が存在しているのか確認してみよう。

In [21]:
dir(pd)

['Categorical',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'ExcelFile',
 'ExcelWriter',
 'Expr',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int64Index',
 'Interval',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Panel4D',
 'Period',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseList',
 'SparseSeries',
 'Term',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt64Index',
 'WidePanel',
 '_DeprecatedModule',
 '__builtins__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__name__',
 '__package__',
 '__path__',
 '__version__',
 '__warningregistry__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p10',
 '_np_version_under1p11',
 '_np_version_under1p12',
 '_np_version_under1p8',
 '_np_version_under1p9',
 '_tslib',
 '_version',
 'api',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'datetime',
 'datetools',
 'describe_option',
 'errors

In [22]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__name__',
 '__package__',
 '__path__',
 '__version__',
 '_distributor_init',
 '_globals',
 '_import_tools',
 '_mat',
 'abs',
 'absolute',
 'absolute_import',
 'ad

例えばnpオブジェクトに存在するarray関数へのアクセスはnp.arrayでアクセスする。ちょっと確認してみよう

In [23]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

では、これではできないのか？

In [24]:
array([1,2,3,4])

NameError: name 'array' is not defined

そんな関数は定義されていないぞと、怒られます。

ただ、設定さえすれば、関数単位で利用できるようにすることも可能

例えば下記のように

In [25]:
from numpy import array

In [26]:
array([1,2,3,4])
#これでarrayという名前で関数が利用できるようになった。

array([1, 2, 3, 4])

全てを指定するのが面倒ということなら

In [27]:
from numpy import *

In [31]:
zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

ということも可能

ただし、オブジェクトは上書きされてしまうので、名前が被らないように命名規則などきちんと決めておく必要がある。